# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_find_and_replace_docx(object):
    def setupUi(self, find_and_replace_docx):
        find_and_replace_docx.setObjectName("find_and_replace_docx")
        find_and_replace_docx.setEnabled(True)
        find_and_replace_docx.resize(450, 475)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(find_and_replace_docx.sizePolicy().hasHeightForWidth())
        find_and_replace_docx.setSizePolicy(sizePolicy)
        find_and_replace_docx.setMinimumSize(QtCore.QSize(450, 475))
        find_and_replace_docx.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.centralwidget = QtWidgets.QWidget(find_and_replace_docx)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_dir = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_dir.setFont(font)
        self.lineEdit_dir.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_dir.setObjectName("lineEdit_dir")
        self.lineEdit_dir.setStatusTip('directory path')
        self.horizontalLayout_2.addWidget(self.lineEdit_dir)
        self.pushButton_browse = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_browse.setFont(font)
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.pushButton_browse.setStatusTip('Directory Overview')
        self.horizontalLayout_2.addWidget(self.pushButton_browse)
        self.checkBox_subdir = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_subdir.setEnabled(True)
        self.checkBox_subdir.setObjectName("checkBox_subdir")
        self.checkBox_subdir.setStatusTip('search files in subdirectories?')
        self.gridLayout_2.addWidget(self.checkBox_subdir, 2, 0, 1, 1)

        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        # создание шапки
            # создание наименование столбца поиска
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
            # создание наименование столбца заменямого текста
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)

        # кусок создающий прописью № строчки
        self.label_number_1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_number_1.setFont(font)
        self.label_number_1.setObjectName("label_number_1")
        self.gridLayout.addWidget(self.label_number_1, 1, 0, 1, 1)
        # кусок создание строки для ввода искомого значения
        self.lineEdit_search_text_1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_search_text_1.setFont(font)
        self.lineEdit_search_text_1.setObjectName("lineEdit_search_text_1")
        self.lineEdit_search_text_1.setStatusTip('search text (original)')
        self.gridLayout.addWidget(self.lineEdit_search_text_1, 1, 1, 1, 1)
        # кусок создает стрелочку
        self.arrow_symbol_1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.arrow_symbol_1.setFont(font)
        self.gridLayout.addWidget(self.arrow_symbol_1, 1, 2, 1, 1)
        # кусок создает строку для ввода заменяемого текста
        self.lineEdit_replaced_by_1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_replaced_by_1.setFont(font)
        self.lineEdit_replaced_by_1.setObjectName("lineEdit_replaced_by_1")
        self.lineEdit_replaced_by_1.setStatusTip('replacement text (new)')
        self.gridLayout.addWidget(self.lineEdit_replaced_by_1, 1, 3, 1, 1)

        # кусок создающий прописью № строчки
        self.label_number_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_number_2.setFont(font)
        self.label_number_2.setObjectName("label_number_2")
        self.gridLayout.addWidget(self.label_number_2, 2, 0, 1, 1)
        # кусок создание строки для ввода искомого значения
        self.lineEdit_search_text_2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_search_text_2.setFont(font)
        self.lineEdit_search_text_2.setObjectName("lineEdit_search_text_2")
        self.gridLayout.addWidget(self.lineEdit_search_text_2, 2, 1, 1, 1)
        # кусок создает стрелочку
        self.arrow_symbol_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.arrow_symbol_2.setFont(font)
        self.gridLayout.addWidget(self.arrow_symbol_2, 2, 2, 1, 1)
        # кусок создает строку для ввода заменяемого текста
        self.lineEdit_replaced_by_2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_replaced_by_2.setFont(font)
        self.lineEdit_replaced_by_2.setObjectName("lineEdit_replaced_by_2")
        self.gridLayout.addWidget(self.lineEdit_replaced_by_2, 2, 3, 1, 1)

        # кусок создающий прописью № строчки
        self.label_number_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_number_3.setFont(font)
        self.label_number_3.setObjectName("label_number_3")
        self.gridLayout.addWidget(self.label_number_3, 3, 0, 1, 1)
        # кусок создание строки для ввода искомого значения
        self.lineEdit_search_text_3 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_search_text_3.setFont(font)
        self.lineEdit_search_text_3.setObjectName("lineEdit_search_text_3")
        self.gridLayout.addWidget(self.lineEdit_search_text_3, 3, 1, 1, 1)
        # кусок создает стрелочку
        self.arrow_symbol_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.arrow_symbol_3.setFont(font)
        self.gridLayout.addWidget(self.arrow_symbol_3, 3, 2, 1, 1)
        # кусок создает строку для ввода заменяемого текста
        self.lineEdit_replaced_by_3 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_replaced_by_3.setFont(font)
        self.lineEdit_replaced_by_3.setObjectName("lineEdit_replaced_by_3")
        self.gridLayout.addWidget(self.lineEdit_replaced_by_3, 3, 3, 1, 1)

        # кусок создающий прописью № строчки
        self.label_number_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_number_4.setFont(font)
        self.label_number_4.setObjectName("label_number_4")
        self.gridLayout.addWidget(self.label_number_4, 4, 0, 1, 1)
        # кусок создание строки для ввода искомого значения
        self.lineEdit_search_text_4 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_search_text_4.setFont(font)
        self.lineEdit_search_text_4.setObjectName("lineEdit_search_text_4")
        self.gridLayout.addWidget(self.lineEdit_search_text_4, 4, 1, 1, 1)
        # кусок создает стрелочку
        self.arrow_symbol_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.arrow_symbol_4.setFont(font)
        self.gridLayout.addWidget(self.arrow_symbol_4, 4, 2, 1, 1)
        # кусок создает строку для ввода заменяемого текста
        self.lineEdit_replaced_by_4 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_replaced_by_4.setFont(font)
        self.lineEdit_replaced_by_4.setObjectName("lineEdit_replaced_by_4")
        self.gridLayout.addWidget(self.lineEdit_replaced_by_4, 4, 3, 1, 1)

        # кусок создающий прописью № строчки
        self.label_number_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_number_5.setFont(font)
        self.label_number_5.setObjectName("label_number_5")
        self.gridLayout.addWidget(self.label_number_5, 5, 0, 1, 1)
        # кусок создание строки для ввода искомого значения
        self.lineEdit_search_text_5 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_search_text_5.setFont(font)
        self.lineEdit_search_text_5.setObjectName("lineEdit_search_text_5")
        self.gridLayout.addWidget(self.lineEdit_search_text_5, 5, 1, 1, 1)
        # кусок создает стрелочку
        self.arrow_symbol_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.arrow_symbol_5.setFont(font)
        self.gridLayout.addWidget(self.arrow_symbol_5, 5, 2, 1, 1)
        # кусок создает строку для ввода заменяемого текста
        self.lineEdit_replaced_by_5 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_replaced_by_5.setFont(font)
        self.lineEdit_replaced_by_5.setObjectName("lineEdit_replaced_by_5")
        self.gridLayout.addWidget(self.lineEdit_replaced_by_5, 5, 3, 1, 1)

        # кусок создающий прописью № строчки
        self.label_number_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_number_6.setFont(font)
        self.label_number_6.setObjectName("label_number_6")
        self.gridLayout.addWidget(self.label_number_6, 6, 0, 1, 1)
        # кусок создание строки для ввода искомого значения
        self.lineEdit_search_text_6 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_search_text_6.setFont(font)
        self.lineEdit_search_text_6.setObjectName("lineEdit_search_text_6")
        self.gridLayout.addWidget(self.lineEdit_search_text_6, 6, 1, 1, 1)
        # кусок создает стрелочку
        self.arrow_symbol_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.arrow_symbol_6.setFont(font)
        self.gridLayout.addWidget(self.arrow_symbol_6, 6, 2, 1, 1)
        # кусок создает строку для ввода заменяемого текста
        self.lineEdit_replaced_by_6 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_replaced_by_6.setFont(font)
        self.lineEdit_replaced_by_6.setObjectName("lineEdit_replaced_by_5")
        self.gridLayout.addWidget(self.lineEdit_replaced_by_6, 6, 3, 1, 1)

        # кусок создающий прописью № строчки. ЗАМЕНИТЬ НА КНОПКУ ДОБАВИТЬ ПОЛЕ И НАСТРОИТЬ ЕЕ
        self.label_number_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_number_7.setFont(font)
        self.label_number_7.setObjectName("label_number_7")
        self.gridLayout.addWidget(self.label_number_7, 7, 0, 1, 1)
        # кусок создание строки для ввода искомого значения
        self.lineEdit_search_text_7 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_search_text_7.setFont(font)
        self.lineEdit_search_text_7.setObjectName("lineEdit_search_text_7")
        self.gridLayout.addWidget(self.lineEdit_search_text_7, 7, 1, 1, 1)
        # кусок создает стрелочку
        self.arrow_symbol_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.arrow_symbol_7.setFont(font)
        self.gridLayout.addWidget(self.arrow_symbol_7, 7, 2, 1, 1)
        # кусок создает строку для ввода заменяемого текста
        self.lineEdit_replaced_by_7 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_replaced_by_7.setFont(font)
        self.lineEdit_replaced_by_7.setObjectName("lineEdit_replaced_by_5")
        self.gridLayout.addWidget(self.lineEdit_replaced_by_7, 7, 3, 1, 1)

        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 1)  # отвечает за кусок с поиском-заменой текста

        self.checkBox_changes = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_changes.setObjectName("checkBox_changes")
        self.checkBox_changes.setStatusTip('keep a copy of the source files?')
        self.gridLayout_2.addWidget(self.checkBox_changes, 6, 0, 1, 1)

        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.label_dir = QtWidgets.QLabel(self.centralwidget)
        self.label_dir.setMinimumSize(QtCore.QSize(347, 0))
        self.label_dir.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_dir.setFont(font)
        self.label_dir.setObjectName("label_dir")
        self.gridLayout_2.addWidget(self.label_dir, 0, 0, 1, 1)
        self.pushButton_convert = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_convert.setFont(font)
        self.pushButton_convert.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.pushButton_convert.setStatusTip('Start Replacing')
        self.gridLayout_2.addWidget(self.pushButton_convert, 12, 0, 1, 1)

        self.label_count_files = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_count_files.setFont(font)
        self.label_count_files.setObjectName("label_count_files")
        self.gridLayout_2.addWidget(self.label_count_files, 7, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")

        '''
        #ТУТ НАЧИНАЕТСЯ КУСОК С НЕРАБОЧЕЙ КНОПКОЙ
        self.pushButton_add_line = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_line.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add_line.sizePolicy().hasHeightForWidth())
        self.pushButton_add_line.setSizePolicy(sizePolicy)
        self.pushButton_add_line.setMinimumSize(QtCore.QSize(10, 10))
        self.pushButton_add_line.setMaximumSize(QtCore.QSize(200, 20000))
        self.pushButton_add_line.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_add_line.setFont(font)
        self.pushButton_add_line.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_add_line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_add_line.setObjectName("pushButton_add_line")
        self.horizontalLayout.addWidget(self.pushButton_add_line)
        '''

        self.gridLayout_2.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(375, 15))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 10, 0, 1, 1)
        find_and_replace_docx.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(find_and_replace_docx)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        find_and_replace_docx.setMenuBar(self.menuBar)

        self.actionExit = QtWidgets.QAction(find_and_replace_docx)
        self.actionExit.setObjectName("actionExit")
        self.actionExit.setShortcut('Ctrl+Q')
        self.actionExit.setStatusTip('Exit application')
        self.actionExit.triggered.connect(QtWidgets.qApp.quit)

        self.about = QtWidgets.QAction(find_and_replace_docx)
        self.about.setObjectName("About_the_program")
        self.about.setStatusTip('About the program')

        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.about)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(find_and_replace_docx)
        QtCore.QMetaObject.connectSlotsByName(find_and_replace_docx)

    def retranslateUi(self, find_and_replace_docx):
        _translate = QtCore.QCoreApplication.translate
        find_and_replace_docx.setWindowTitle(_translate("find_and_replace_docx", "find_and_replace_docx"))
        self.pushButton_browse.setText(_translate("find_and_replace_docx", "browse"))
        self.label_dir.setText(_translate("find_and_replace_docx", "Directory:"))
        self.pushButton_convert.setText(_translate("find_and_replace_docx", "Convert"))
        self.label_number_5.setText(_translate("find_and_replace_docx", "5"))
        self.label_number_4.setText(_translate("find_and_replace_docx", "4"))
        self.label_number_6.setText(_translate("find_and_replace_docx", "6"))
        self.label_number_7.setText(_translate("find_and_replace_docx", "7"))
        self.label_number_2.setText(_translate("find_and_replace_docx", "2"))
        self.label_number_3.setText(_translate("find_and_replace_docx", "3"))
        self.label_number_1.setText(_translate("find_and_replace_docx", "1"))
        self.label.setText(_translate("find_and_replace_docx", "search text:"))
        self.arrow_symbol_1.setText(_translate("find_and_replace_docx", "→"))
        self.arrow_symbol_2.setText(_translate("find_and_replace_docx", "→"))
        self.arrow_symbol_3.setText(_translate("find_and_replace_docx", "→"))
        self.arrow_symbol_4.setText(_translate("find_and_replace_docx", "→"))
        self.arrow_symbol_5.setText(_translate("find_and_replace_docx", "→"))
        self.arrow_symbol_6.setText(_translate("find_and_replace_docx", "→"))
        self.arrow_symbol_7.setText(_translate("find_and_replace_docx", "→"))
        self.label_3.setText(_translate("find_and_replace_docx", "replaced by:"))
        self.checkBox_subdir.setText(_translate("find_and_replace_docx", "Search files in subdirectories"))
        self.checkBox_changes.setText(_translate("find_and_replace_docx", "Make changes to file copies"))
        self.label_count_files.setText(_translate("find_and_replace_docx", "Found 0 files"))
        #self.pushButton_add_line.setText(_translate("find_and_replace_docx", "Add line"))
        self.menuFile.setTitle(_translate("find_and_replace_docx", "File"))
        self.menuAbout.setTitle(_translate("find_and_replace_docx", "About"))
        self.actionExit.setText(_translate("find_and_replace_docx", "exit"))
        self.about.setText(_translate("find_and_replace_docx", "about"))

